---
title: "Pink Tax Spain"
author: "Phong Duong, Nienke Visscher"
date: "2024-02-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Library

```{r}
library(xml2)
library(httr)
library(tidyverse)
library(sf)
library(rnaturalearth)
library(scrapex)
library(RSelenium)
library(magrittr)
library(lubridate)
library(dplyr)
library(tidyr)


```

## Mercadona

```{r}
set_config(
  user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36; Nienke Visscher / nienvis@gmail.com")
)

#Code for attaching JAVA
#Sys.getenv("JAVA_HOME")
#Sys.setenv(JAVA_HOME = "C:/Program Files/Common Files/Oracle/Java/javapath/java.exe")
#Sys.getenv("PATH")
#install.packages("RSelenium", dependencies = TRUE)

#Opening hidden browser
remDr <- rsDriver(port = 4462L, browser = "firefox",  verbose=F, chromever = NULL)


merc <-"https://tienda.mercadona.es/categories"

browseURL(prep_browser(merc))
 
remDr$client$navigate(merc)


```

```{r}

driver <- remDr$client

#Note following only when having newly initiated the port
#Accepting cookies
driver$findElement(value = "(//button[@class = 'ui-button ui-button--small ui-button--tertiary ui-button--positive'])[1]")$clickElement()

#Click on text box
driver$findElement(value = "(//input[@class = 'ym-hide-content'])[1]")$clickElement()

#Define findElement of the textbox
codigo <-driver$findElement(value = "(//input[@class = 'ym-hide-content'])[1]")

#Fill in the text box
codigo$sendKeysToElement(list("28014"))

#Click 
driver$findElement(value = "(//button[@class = 'button button-primary button-big'])[1]")$clickElement()

##### Until here


#Insert below
cat_name <- cat_html |> 
   xml_find_all("//label[@class='subhead1-r']") |>
   xml_text()


#Get URL first categories
url <- list()
  
driver$findElement(value = "(//label[@class='subhead1-r' and contains(text(), 'Cuidado del cabello')])[1]")$clickElement()

Sys.sleep(1)

url[1] <-driver$getCurrentUrl()


for (i in (2:4)){
  
  driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()
  
Sys.sleep(1)
  
  url[i] <-driver$getCurrentUrl()
  
  
}

#Get URL second categories
  
driver$findElement(value = "(//label[@class='subhead1-r' and contains(text(), 'Cuidado facial y corporal')])[1]")$clickElement()

Sys.sleep(1)

url[5] <-driver$getCurrentUrl()



for (i in (6:15)){
  
  
  driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()
  
  Sys.sleep(1)
  
  url[i] <-driver$getCurrentUrl()
  
}


url <-unlist(url)


```

```{r}


cat_grabber <- function(url){
  

driver$navigate(url)
  
Sys.sleep(1)

cat_html <-driver$getPageSource()[[1]] |>
  read_html() 

cat_info <- cat_html|> 
    xml_find_all("//*[@id='root']//button/div[2]") |>
    xml_text()

subcat_name <- cat_html |> 
   xml_find_all("//h1[@class='category-detail__title title1-b']") |>
   xml_text()


cat_clean<-cat_info|> 
  str_replace_all("\\€ |/|\\.|!", "") |>
  str_replace_all("\\€\\d+,\\d+", "") |>
  str_replace_all("(?<=\\d\\s)ml", "/ml/") |> 
  str_replace_all("(?<=\\d\\s)ud", "/ud/") |> 
  str_replace_all("(?<=\\d\\s{0,2})ud", "/ud/") |> 
  str_replace_all("(?<=\\d\\s)L", "/L/") |> 
  str_replace_all("(?<=\\d\\s)tarro", "") |> 
  str_replace_all("(?<=\\d\\s)g\\s", "/g/") |> 
  str_replace_all("(?<=\\d\\s)sobres", "/sobres/") |> 
  str_replace_all("(?<=\\d\\s)bandas", "/bandas/") |> 
  str_replace_all("(?<=sensibleCaja\\s)1", "/") |> 
  str_replace_all("(?<=DovePaquete\\s)4", "/") |> 
  str_replace_all("ud.(?=\\s*\\()", "") |> 
  str_replace_all("\\s(?=\\d+\\s*/)", "/") |> 
  str_replace_all("(?<=[[:lower:]])(?=[[:digit:]])", "/") |> 
  str_replace_all("\\(|\\)", "") |> 
  str_replace_all("\\.", "")|> 
  strsplit("/")


cat_clean <- lapply(cat_clean, function(x) {
  length(x) <- 5
  x
})


cat_clean<- cat_clean[lengths(cat_clean) <= 5]

data.frame(
  name = sapply(cat_clean, `[`, 1),
  quantity = sapply(cat_clean, `[`, 2),
  quantity_unit = sapply(cat_clean, `[`, 3),
  price = sapply(cat_clean, `[`, 4),
  ud =  sapply(cat_clean, `[`, 5),
  subcat =  sapply(subcat_name, `[`, 1),
  stringsAsFactors = FALSE
)


}

cat_grabber(url)


final <- map_dfr(url, cat_grabber) 

```

```{r}
driver$navigate(url[1])


cat_html <-driver$getPageSource()[[1]] |>
  read_html() 



cat_info <- cat_html|> 
    xml_find_all("//*[@id='root']//button/div[2]") |>
    xml_text()

cat_clean<-cat_info|> 
  str_replace_all("\\€ |/|\\.|!", "") |>
  str_replace_all("\\€\\d+,\\d+", "") |>
  str_replace_all("(?<=\\d\\s)ml", "/ml/") |> 
  str_replace_all("(?<=\\d\\s)ud", "/ud/") |> 
  str_replace_all("(?<=\\d\\s)L", "/L/") |> 
  str_replace_all("(?<=\\d\\s)tarro", "") |> 
  str_replace_all("(?<=\\d\\s)g\\s", "/g/") |> 
  str_replace_all("(?<=\\d\\s)sobres", "/sobres/") |> 
  str_replace_all("(?<=\\d\\s)bandas", "/bandas/") |> 
  str_replace_all("(?<=sensibleCaja\\s)1", "/") |> 
  str_replace_all("(?<=DovePaquete\\s)4", "/") |> 
  str_replace_all("ud.(?=\\s*\\()", "") |> 
  str_replace_all("\\s(?=\\d+\\s*/)", "/") |> 
  str_replace_all("(?<=[[:lower:]])(?=[[:digit:]])", "/") |> 
  str_replace_all("\\(|\\)", "") |> 
  str_replace_all("\\.", "")|> 
  strsplit("/")


cat_info[24]


cat_clean[24]
```

## deleted

```{r}

cat_clean<-cat_info|> 
   str_replace_all("ml|€|/ud|L|\\.", "") |> 
   strsplit("\\s(?=\\d)", perl = TRUE)

driver$navigate(total_url_ul[3])

cat_html <-driver$getPageSource()[[1]] |>
  read_html() 

cat_info <- cat_html|> 
    xml_find_all("//*[@id='root']//button/div[2]") |>
    xml_text()

cat_info

cat_clean<-cat_info|> 
  str_replace_all("\\€ |/|\\.", "") |> 
  strsplit("\\s(?=\\d+\\s*ud)|\\.*ud|\\s(?=\\d+\\s*ml)|ml|L", perl = TRUE) 
cat_clean

cat_clean_filter<- cat_clean[lengths(cat_clean) <= 3]

data.frame(
  name = sapply(cat_clean_filter, `[`, 1),
  quantity = sapply(cat_clean_filter, `[`, 2),
  price = sapply(cat_clean_filter, `[`, 3),
  stringsAsFactors = FALSE
)

```

Fully automate

```{r}

#automate
url <- list()

driver <- remDr$client
cat <- "Cuidado del cabello"

url_grabber<-function(cat){
  
driver$findElement(value = paste("(//label[@class='subhead1-r' and contains(text()," ,cat, ")])[1]", sep = ""))$clickElement()

url[1] <-driver$getCurrentUrl()

for (i in (2:4)){
  
  driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()
  
  url[i] <-driver$getCurrentUrl()
  
}
}

```

```{r}
#Get URLs

#Click on Cuidado del cabello
driver$findElement(value = "(//label[@class='subhead1-r' and contains(text(), 'Cuidado del cabello')])[1]")$clickElement()

url_1.1 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_1.2 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_1.3 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_1.4 <-driver$getCurrentUrl()

#Click on Cuidado facial y corporal
driver$findElement(value = "(//label[@class='subhead1-r' and contains(text(), 'Cuidado facial y corporal')])[1]")$clickElement()

url_2.1 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.2 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.3 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.4 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.5 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.6 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.7 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.8 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.9 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.10 <-driver$getCurrentUrl()

driver$findElement(value = "(//button[@class = 'ui-button ui-button--big ui-button--secondary ui-button--positive category-detail__next-subcategory'])[1]")$clickElement()

url_2.11 <-driver$getCurrentUrl()

```
